services:
  - type: web
    name: lol-rank-checker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RIOT_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
